### ISSUE TITLE
Mismatch between local site and deployed site

### ISSUE THREAD

**Issue by jillsuecamp** [jillsuecamp/HenHacks#1]
When running ```bundle exec jekyll serve ```, the local site has an entirely different (and more stylistically desirable) layout than the deployed site (looks like raw HTML). Right click on the deployed site and inspect the console to diagnose any issues with the CSS loading properly.

**Comment by jillsuecamp** [comment]
Is this a problem with the build that gh pages is doing? 
<img width="1440" alt="Screen Shot 2023-10-23 at 12 48 03 AM" src="https://github.com/jillsuecamp/HenHacks/assets/92810033/c082851b-1c33-4cf5-ad59-004c40b016ec">
<img width="1440" alt="Screen Shot 2023-10-23 at 12 47 41 AM" src="https://github.com/jillsuecamp/HenHacks/assets/92810033/4cbe2895-b87b-47d9-8166-f2b6aa703816">

**Comment by OneTachi** [comment]
I think this has to do with an unchanged line in the _config.yml file. 
![image](https://github.com/jillsuecamp/HenHacks/assets/52607373/07fc63dc-1b24-4f9b-bd02-8c58b2a9212f)

There's no real way to test this change, so I'll be pushing changes to the line described above to see if it changes.

**Comment by OneTachi** [comment]
Mhmm, it seems that did not work. 
![image](https://github.com/jillsuecamp/HenHacks/assets/52607373/9a32690f-a606-4538-a2e0-2a58dadc1c8d)

I did omit the '/' at the end of the url link which I think shouldn't affect it. Jill could you try adding the / to the url and pushing it to a separate branch and having gh pages launch off that branch? I don't really like the idea of pushing more changes to the main branch without knowing if it worked or not

**Comment by OneTachi** [comment]
The other change that should fix this issue is one of the first lines in _config.yml: 
![Image](https://github.com/jillsuecamp/HenHacks/assets/52607373/e6533848-e72d-4a8a-a4ff-f255b37b72ae)
